IS_PINYIN = 1 << 1
IS_ZHUYIN = 1 << 2
PINYIN_INCOMPLETE = 1 << 3
ZHUYIN_INCOMPLETE = 1 << 4
USE_TONE = 1 << 5
FORCE_TONE = 1 << 6
USE_DIVIDED_TABLE = 1 << 7
USE_RESPLIT_TABLE = 1 << 8
DYNAMIC_ADJUST = 1 << 9

PINYIN_AMB_C_CH = 1 << 10
PINYIN_AMB_S_SH = 1 << 11
PINYIN_AMB_Z_ZH = 1 << 12
PINYIN_AMB_F_H = 1 << 13
PINYIN_AMB_G_K = 1 << 14
PINYIN_AMB_L_N = 1 << 15
PINYIN_AMB_L_R = 1 << 16
PINYIN_AMB_AN_ANG = 1 << 17
PINYIN_AMB_EN_ENG = 1 << 18
PINYIN_AMB_IN_ING = 1 << 19
PINYIN_AMB_ALL = 0x3FF << 10

PINYIN_CORRECT_GN_NG = 1 << 21
PINYIN_CORRECT_MG_NG = 1 << 22
PINYIN_CORRECT_IOU_IU = 1 << 23
PINYIN_CORRECT_UEI_UI = 1 << 24
PINYIN_CORRECT_UEN_UN = 1 << 25
PINYIN_CORRECT_UE_VE = 1 << 26
PINYIN_CORRECT_V_U = 1 << 27
PINYIN_CORRECT_ON_ONG = 1 << 28
PINYIN_CORRECT_ALL = 0xFF << 21

ZHUYIN_CORRECT_HSU = 1 << 29
ZHUYIN_CORRECT_ETEN26 = 1 << 30
ZHUYIN_CORRECT_SHUFFLE = 1 << 31
ZHUYIN_CORRECT_ALL = 0x7 << 29

FULL_PINYIN_HANYU = 1
FULL_PINYIN_LUOMA = 2
FULL_PINYIN_SECONDARY_ZHUYIN = 3
FULL_PINYIN_DEFAULT = FULL_PINYIN_HANYU

DOUBLE_PINYIN_ZRM = 1
DOUBLE_PINYIN_MS = 2
DOUBLE_PINYIN_ZIGUANG = 3
DOUBLE_PINYIN_ABC = 4
DOUBLE_PINYIN_PYJJ = 5
DOUBLE_PINYIN_XHE = 6
DOUBLE_PINYIN_CUSTOMIZED = 30
DOUBLE_PINYIN_DEFAULT = DOUBLE_PINYIN_MS

ZHUYIN_STANDARD = 1
ZHUYIN_HSU = 2
ZHUYIN_IBM = 3
ZHUYIN_GINYIEH = 4
ZHUYIN_ETEN = 5
ZHUYIN_ETEN26 = 6
ZHUYIN_STANDARD_DVORAK = 7
ZHUYIN_HSU_DVORAK = 8
ZHUYIN_DACHEN_CP26 = 9
ZHUYIN_DEFAULT = ZHUYIN_STANDARD

NBEST_MATCH_CANDIDATE = 1
NORMAL_CANDIDATE = 2
ZOMBIE_CANDIDATE = 3
PREDICTED_CANDIDATE = 4
ADDON_CANDIDATE = 5

SORT_BY_PHRASE_LENGTH_AND_FREQUENCY = 1
SORT_BY_PHRASE_LENGTH_AND_PINYIN_LENGTH_AND_FREQUENCY = 2

GB_DICTIONARY = 1
TSI_DICTIONARY = 1
GBK_DICTIONARY = 2
OPENGRAM_DICTIONARY = 3
MERGED_DICTIONARY = 4
ADDON_DICTIONARY = 5
NETWORK_DICTIONARY = 6
USER_DICTIONARY = 7

PHRASE_MASK = 0x00FFFFFF
PHRASE_INDEX_LIBRARY_MASK = 0x0F000000
PHRASE_INDEX_LIBRARY_COUNT = 1 << 4
null_token = 0


def PHRASE_INDEX_MAKE_TOKEN(phrase_index, token):
    return (((phrase_index << 24) & PHRASE_INDEX_LIBRARY_MASK) |
            (token & PHRASE_MASK))
